#!/bin/bash -e
#
# Based on example from here: http://manpages.ubuntu.com/manpages/bionic/man7/debconf-devel.7.html
#

CONFIGFILE=/etc/tg-torrent-bot/main.conf

. /usr/share/debconf/confmodule

# Generate config file, if it doesn't exist.
# An alternative is to copy in a template
# file from elsewhere.
if [ ! -e $CONFIGFILE ]; then
    echo '# Telegram Torrent Bot configuration'                    > $CONFIGFILE
    echo ''                                                       >> $CONFIGFILE
    echo 'TELEGRAM_TOKEN='                                        >> $CONFIGFILE
    echo 'RUTRACKER_USERNAME='                                    >> $CONFIGFILE
    echo 'RUTRACKER_PASSWORD='                                    >> $CONFIGFILE
    echo 'TORRENTS_DIR='                                          >> $CONFIGFILE
    echo 'ALLOWED_USERS='                                         >> $CONFIGFILE
    echo 'RUTRACKER_HOST="http://rutracker.org"'                  >> $CONFIGFILE
    echo ''                                                       >> $CONFIGFILE
    echo '# Should the bot use proxy to access Telegram servers?' >> $CONFIGFILE
    echo 'PROXY_TELEGRAM="false"'                                 >> $CONFIGFILE
    echo ''                                                       >> $CONFIGFILE
    echo '# Should the bot use proxy to access rutracker.org?'    >> $CONFIGFILE
    echo 'PROXY_RUTRACKER="false"'                                >> $CONFIGFILE
    echo ''                                                       >> $CONFIGFILE
    echo '# Proxy settings'                                       >> $CONFIGFILE
    echo 'PROXY_HOST="127.0.0.1"'                                 >> $CONFIGFILE
    echo 'PROXY_PORT="8080"'                                      >> $CONFIGFILE
    echo 'PROXY_USERNAME='                                        >> $CONFIGFILE
    echo 'PROXY_PASSWORD='                                        >> $CONFIGFILE
    echo ''                                                       >> $CONFIGFILE
fi

# Substitute in the values from the debconf db.
# There are obvious optimizations possible here.
# The cp before the sed ensures we do not mess up
# the config file's ownership and permissions.
db_get tg-torrent-bot/telegram_token
TELEGRAM_TOKEN="$RET"
db_get tg-torrent-bot/rutracker_username
RUTRACKER_USERNAME="$RET"
db_get tg-torrent-bot/rutracker_password
RUTRACKER_PASSWORD="$RET"
db_get tg-torrent-bot/torrents_dir
TORRENTS_DIR="$RET"
cp -a -f $CONFIGFILE $CONFIGFILE.tmp

# If the admin deleted or commented some variables but then set
# them via debconf, (re-)add them to the conffile.
test -z "$TELEGRAM_TOKEN" || grep -Eq '^ *TELEGRAM_TOKEN=' $CONFIGFILE || \
    echo "TELEGRAM_TOKEN=" >> $CONFIGFILE
test -z "$RUTRACKER_USERNAME" || grep -Eq '^ *RUTRACKER_USERNAME=' $CONFIGFILE || \
    echo "RUTRACKER_USERNAME=" >> $CONFIGFILE
test -z "$RUTRACKER_PASSWORD" || grep -Eq '^ *RUTRACKER_PASSWORD=' $CONFIGFILE || \
    echo "RUTRACKER_PASSWORD=" >> $CONFIGFILE
test -z "$TORRENTS_DIR" || grep -Eq '^ *TORRENTS_DIR=' $CONFIGFILE || \
    echo "TORRENTS_DIR=" >> $CONFIGFILE

sed -e "s#^ *TELEGRAM_TOKEN=.*#TELEGRAM_TOKEN=\"${TELEGRAM_TOKEN//#/\\#}\"#" \
    -e "s#^ *RUTRACKER_USERNAME=.*#RUTRACKER_USERNAME=\"${RUTRACKER_USERNAME//#/\\#}\"#" \
    -e "s#^ *RUTRACKER_PASSWORD=.*#RUTRACKER_PASSWORD=\"${RUTRACKER_PASSWORD//#/\\#}\"#" \
    -e "s#^ *TORRENTS_DIR=.*#TORRENTS_DIR=\"${TORRENTS_DIR//#/\\#}\"#" \
    < $CONFIGFILE > $CONFIGFILE.tmp
mv -f $CONFIGFILE.tmp $CONFIGFILE

#DEBHELPER#

mkdir -p /var/lib/tg-torrent-bot
chown tg-torrent-bot:tg-torrent-bot /var/lib/tg-torrent-bot
