name: Deploy to Heroku

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: worker
        env:
          HD_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          HD_RUTRACKER_USERNAME: ${{ secrets.RUTRACKER_USERNAME }}
          HD_RUTRACKER_PASSWORD: ${{ secrets.RUTRACKER_PASSWORD }}
          HD_RUTRACKER_HOST: "http://rutracker.org"
